/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "9.2.0"
    id("com.gradleup.shadow") version "9.4.1"
}

repositories {
    mavenLocal()
    maven ("https://repo.papermc.io/repository/maven-public/") {
        name = "papermc-repo"
    }
    maven ("https://repo.codemc.io/repository/maven-releases/") {
        name = "codemc-releases"
    }
    maven ("https://jitpack.io") {
        name = "jitpack"
    }
    maven ("https://repo.william278.net/releases/") {
        name = "william278"
    }
    maven ("https://repo.maven.apache.org/maven2/")
}

dependencies {
    implementation("com.github.retrooper:packetevents-velocity:2.12.1")
    implementation("redis.clients:jedis:7.1.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.xerial:sqlite-jdbc:3.53.1.0")
    implementation("com.mysql:mysql-connector-j:9.7.0")
    compileOnly("com.velocitypowered:velocity-api:3.5.0-SNAPSHOT")
    compileOnly("net.skinsrestorer:skinsrestorer-api:15.12.0")
    compileOnly("io.github.miniplaceholders:miniplaceholders-api:3.2.0")
    compileOnly("net.william278:papiproxybridge:1.8.4")
    compileOnly("it.unimi.dsi:fastutil:8.5.18")
    compileOnly(files("lib/floodgate-velocity.jar"))
    annotationProcessor("com.velocitypowered:velocity-api:3.5.0-SNAPSHOT")
}

group = "cn.jason31416"
version = "1.2.2"
description = "ChatX"
java.sourceCompatibility = JavaVersion.VERSION_25
var baseName: String = "ChatX-Beta"

tasks {
    shadowJar {
        relocate("redis.clients", "cn.jason31416.chatx.lib.redis")
        relocate("com.github.retrooper.packetevents", "cn.jason31416.chatx.lib.packetevents")
        relocate("io.github.retrooper.packetevents", "cn.jason31416.chatx.lib.packetevents")
        relocate("com.zaxxer.hikari", "cn.jason31416.chatx.lib.hikari")
        archiveBaseName.set(baseName)
        archiveClassifier.set("")
        minimize()
    }

    jar {
        archiveBaseName.set("original-$baseName")
    }
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
