/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "9.2.0"
    id("com.gradleup.shadow") version "9.4.1"
}

repositories {
    mavenLocal()
    maven ("https://repo.papermc.io/repository/maven-public/") {
        name = "papermc-repo"
    }
    maven ("https://repo.codemc.io/repository/maven-releases/") {
        name = "codemc-releases"
    }
    maven ("https://jitpack.io") {
        name = "jitpack"
    }
    maven ("https://repo.william278.net/releases/") {
        name = "william278"
    }
    maven ("https://repo.maven.apache.org/maven2/")
}

dependencies {
    implementation("com.github.retrooper:packetevents-velocity:2.13.0")
    implementation("net.dv8tion:JDA:6.6.0") {
        exclude(module = "opus-java")
        exclude(module = "tink")
        exclude(group = "org.slf4j", module = "slf4j-api")
    }
    implementation("redis.clients:jedis:7.1.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.xerial:sqlite-jdbc:3.53.1.0")
    implementation("com.mysql:mysql-connector-j:9.7.0")
    compileOnly("com.velocitypowered:velocity-api:3.5.0-SNAPSHOT")
    compileOnly("net.skinsrestorer:skinsrestorer-api:15.9.3")
    compileOnly("io.github.miniplaceholders:miniplaceholders-api:3.1.0")
    compileOnly("net.william278:papiproxybridge:1.8.4")
    compileOnly("it.unimi.dsi:fastutil:8.5.18")
    compileOnly(files("lib/floodgate-velocity.jar"))
    annotationProcessor("com.velocitypowered:velocity-api:3.5.0-SNAPSHOT")
}

group = "cn.jason31416"
version = "1.3.4"
description = "ChatXJT"
java.sourceCompatibility = JavaVersion.VERSION_21
var baseName: String = "ChatX-Beta"

tasks {
    shadowJar {
        relocate("redis.clients", "cn.jason31416.chatx.lib.redis")
        relocate("com.github.retrooper.packetevents", "cn.jason31416.chatx.lib.packetevents")
        relocate("io.github.retrooper.packetevents", "cn.jason31416.chatx.lib.packetevents")
        relocate("com.zaxxer.hikari", "cn.jason31416.chatx.lib.hikari")
        relocate("net.dv8tion.jda", "cn.jason31416.chatx.lib.jda")
        relocate("com.neovisionaries.ws.client", "cn.jason31416.chatx.lib.nvwebsocket")
        relocate("okhttp3", "cn.jason31416.chatx.lib.okhttp")
        relocate("okio", "cn.jason31416.chatx.lib.okio")
        relocate("kotlin", "cn.jason31416.chatx.lib.kotlin")
        relocate("org.jetbrains.annotations", "cn.jason31416.chatx.lib.jetbrains.annotations")
        relocate("gnu.trove", "cn.jason31416.chatx.lib.trove")
        relocate("org.apache.commons.collections4", "cn.jason31416.chatx.lib.commons.collections4")
        relocate("com.fasterxml.jackson", "cn.jason31416.chatx.lib.jackson")
        archiveBaseName.set(baseName)
        archiveClassifier.set("")
        minimize {
            exclude(dependency("org.xerial:sqlite-jdbc"))
            exclude(dependency("com.mysql:mysql-connector-j"))
        }
    }

    jar {
        archiveBaseName.set("original-$baseName")
    }
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
